### ISSUE TITLE
It doesn't work for some reason

### ISSUE THREAD

**Issue by planetcity** [vibedivide/shitsploit-client-release#11]
All of the functions suddenly stopped working

**Comment by Glatrix** [comment]
Yes, I Pretty sure its b/c they are getting ready to put the game on steam so their updating the game to be more (non-hack-able)
if not, then they added a patch that isn't compatible. foe now i suggest getting tamper monkey on your browser and adding esp. aim bot will be hard to come across though.      ~Glatrix
