### ISSUE TITLE
[FEATURE] AimBot Suggestions

### ISSUE THREAD

**Issue by SpoilerRules** [vibedivide/shitsploit-client-release#12]
**Suggestion Tags**
- **_MaxTurnSpeed_**
- **_MinTurnSpeed_**
- **_AimOffset_**
- **_Lock_** (Avoiding to change Target whenever there a existing Target.)
- **_Chance_** (Chance of AimBot aim into target, if the randomizer hasn't passed the chance, then AimBot'll don't work (so you gotta Aim manually lol))
- **_OnClick_** (AimBot'll only work when you hold the Attack/Shot (or Shoot idk) button)
- **_Remove All Mods on Aimbot_**

**Addional Description**
if all of those'll suggestions added/done, this could be best [Krunker](https://krunker.io) AimBot ever.

**Comment by vibedivide** [comment]
ill consider

**Comment by Glatrix** [comment]
those would be good additions... if its not too much work maybe you could also add a bot? i could go to bed and have the bot farm kr?
