### ISSUE TITLE
Client Patcher Error 

### ISSUE THREAD

**Issue by Sn8ow** [vibedivide/shitsploit-client-release#16]
When opening ShitsPloit an error pops up download patcher. So I downloaded the patcher I chose the shitsploit folder I pressed "Patch" and "Run" but nothing happened but it still asks to download the patcher.

**Comment by vibedivide** [comment]
This client will not be recieving updates. The client patcher is to patch sploit into clients however you are trying to use it in hopes of removing the error code given by the client. You should use the patcher on a official client or try using a userscript.
