### ISSUE TITLE
In-Built Unlock All Skins Hack & AutoGG (AutoMessage on Round End)

### ISSUE THREAD

**Issue by SpoilerRules** [vibedivide/shitsploit-client-release#6]
**Stuff**
- A In-Built Unlock All Skins Hack like tempermonkey scripts & AutoGG (AutoMessage on Round End) for say (customizable) something cool on round end

**Additional Reason**
- I don't like use tampermonkey scripts.

**Comment by vibedivide** [comment]
in a future update ill try to implement a skin hack or once im done fixing it up, the scripting thing for shitsploit will be available with some instructions, also in in-game settings you can scroll to match end message lol

**Comment by SpoilerRules** [comment]
oké

**Comment by SpoilerRules** [comment]
please add skin hack as possible as soon thx

**Comment by hvandoorn** [comment]
yes would be cool
